#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://120.79.153.77:8660/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
server:
  port: 9001
spring:
  application:
    name: user-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #120.79.153.77 192.168.1.191
    url: jdbc:mysql://192.168.1.191:3306/mydb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: wawzj7788
    ################Redis
    #连接第0个库
  redis:
    database: 0
    #连接的地址
    host: 192.168.1.191
    #超时时间：单位ms
    timeout: 3000
    #端口号
    port: 6380
    ##最大连接数：能够同时建立的“最大链接个数”
    pool:
      maxActive: 2000
      #最大空闲数：空闲链接数大于maxIdle时，将进行回收
      maxIdle: 200
      #最小空闲数：低于minIdle时，将创建新的链接
      minIdle: 200
      #最大等待时间：单位ms
      maxWait: 1000
      #服务的名称
#修改调用超时时间
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 1000
#mybatis 下划线转驼峰 映射配置  有了这个不用写xml
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #打印sql 方便调试
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #mapper-locations: mybatis/**/*Mapper.xml
#通用mapper
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL
#page分页配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql